SmartReward/SmartReward/Controllers/BindingController.cs
using SmartReward.Filters;
using SmartReward.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartReward.Helpers;
using SmartReward.Models;
using PagedList;

namespace SmartReward.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class BindingController : Controller
    {
        private SmartRewardEntities db = new SmartRewardEntities();

        public ActionResult AutoComplete(string term)
        {
            var model = db.Users
                .Where(u => u.Email.StartsWith(term))
                .Take(5)
                .Select(r => new { label = r.Email });
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Binding/

        public ActionResult Index(string searchTerm = null, int page = 1)
        {
            
            var model = new BindingViewModel();
            var user = User.GetSmartRewardUser(db);
            model.result = db.Users
                .Where(u => u.UserId != user.UserId && (searchTerm == null || u.Email.Contains(searchTerm)))
                .OrderBy(u => u.UserId)
                .ToPagedList(page, 10);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Members", model);
            }

            return View(model);
        }

        public ActionResult BindingChild(int targetId)
        {
            var user = User.GetSmartRewardUser(db);
            var target = db.Users.Find(targetId);

            bool res = user.SendBindingChildRequest(target, db);

            if (Request.IsAjaxRequest())
            {
                return null;
            }
            return RedirectToAction("Index");
        }

        public ActionResult BindingParent(int targetId)
        {
            var user = User.GetSmartRewardUser(db);
            var target = db.Users.Find(targetId);

            bool res = user.SendBindingParentRequest(target, db);

            if (Request.IsAjaxRequest())
            {
                return null;
            }
            return RedirectToAction("Index");
        }

        public ActionResult SendMail(BindingViewModel model)
        {
            if (Request.IsAjaxRequest())
            {
                return null;
            }
            return RedirectToAction("Index");
        }
    }
}

SmartReward/SmartReward/Controllers/DashboardController.cs
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartReward.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/

        public ActionResult Index()
        {
            //IHubContext hub =  GlobalHost.ConnectionManager.GetHubContext<ChatHub>();

            //hub.Clients.Group("a@yopmail.com").addChatMessage("coucou");
            return View();
        }
    }
}

SmartReward/SmartReward/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Tableau de bord";
    ViewBag.Message = "Gérez votre espace Smart Reward";
}

@section head{
    <link rel="stylesheet" type="text/css" href="~/Content/css/dashboard.css">
}

<div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
        <div id="actions">
            <h2>Actions</h2>
            <ul>
                <li>@Html.ActionLink("Consulter mon cercle", "Index", "TODO")</li>
                <li>@Html.ActionLink("Editer mon catalogue", "Index", "TODO")</li>
                <li>@Html.ActionLink("Editer ma tasklist", "Index", "TODO")</li>
                <li>@Html.ActionLink("Rechercher un membre", "Index", "Binding")</li>
            </ul>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/SmartReward/Dashboard.js"></script>
}